server:
  port: 8080

spring:
  application:
    name: Document-Anaylzer
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b
      embedding:
        options:
          model: nomic-embed-text